apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    context: docker-k8s-lab
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: "MYSQL_USER"
          value: "aldo"
        - name: "MYSQL_PASSWORD"
          value: "senha"
        - name: "MYSQL_DATABASE"
          value: "aula_infra"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "senha"
      ports:
        - containerPort: 3306